spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/datawarehouse"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org.example: DEBUG

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'